### ISSUE TITLE
May support spectree rather than just copying core code

### ISSUE THREAD

**Issue by gaoyibin0001** [turner-townsend/flask-pydantic-spec#17]

**Comment by cgearing** [comment]
Hi there,
Thanks for opening this issue.  

We took the decision to do a fork of `spectree` as at the time we wanted to make some significant changes to the code, and we needed this to be done fairly quickly as we wanted to use the library in production in our application.  We also do not have any expertise with the alternative web frameworks supported by `spectree`, and so didn't feel like we would be able to support the changes we wanted to make (such as allowing for file uploads/responses).

Over time this library will move further away from `spectree`, we will probably remove the indirection around the backend so we only support `flask`, and will try and add more typing to the validator decorator.

Thanks!

**Comment by gaoyibin0001** [comment]
understood, thanks
