### ISSUE TITLE
Support Python types in Response

### ISSUE THREAD

**Issue by matheusads** [turner-townsend/flask-pydantic-spec#55]
Hello,
I started using this library recently and notice that I can't use Python types in Response.

Example:

`@api.validate(query=PropertyQueryModel, resp=Response(HTTP_200=list[PropertyModel]), tags=['properties'])`

This raises an Assertion Error from Response __init__
`assert issubclass(value, BaseModel), "invalid `pydantic.BaseModel`"`

I think could be a good improvement to accept Python types, makes sense?
Quickly looking at the code I didn't find other points where it could affect.

Maybe I can help in this part.
Best.

**Comment by cgearing** [comment]
Would you expect this to be a bare array of that type in the generated OpenAPI spec?

i.e:
```
{
  "description": "Some response",
  "content": {
    "application/json": {
      "schema": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/PropertyModel"
        }
      }
    }
  }
}
```

If you want a quick way of doing this, I have done it elsewhere by creating a Pydantic compatible wrapper type:

```
class PropertyModels(BaseModel):
    __root__: list[ProperyModel]
```

We could definitely look at how that might work though!

**Comment by PeterNociar** [comment]
I made it work [here](https://github.com/turner-townsend/flask-pydantic-spec/pull/57)
Its working for `list[BaseModel]`
