### ISSUE TITLE
[BUG] ImportError

### ISSUE THREAD

**Issue by CharmingZhou** [turner-townsend/flask-pydantic-spec#8]
from flask_pydantic_spec import Validator
ImportError: cannot import name 'Validator'

**Comment by cgearing** [comment]
Ah it looks like I haven't kept the `README.MD` updated!
I'm very sorry about that - I'll get that updated ASAP.

In the meantime, it should be:

`from flask_pydantic_spec import FlaskPydanticSpec`

**Comment by CharmingZhou** [comment]
Thanks
